### ISSUE TITLE
Revision-date issue

### ISSUE THREAD

**Issue by sygsir** [theia-ide/yang-lsp#104]
Hi Jan,

When the “Revision-date” is used within import, now typefox framework support parsing the yangfile@revison-date.yang (for example ericsson-yang-extensions@2018-02-19.yang).

Module ericsson-yang-extensions@2018-02-19 {
Revision “2018-02-19” {
   description "Added preliminary.";
}
}

Module Ericsson-lm {    
            …
            import ericsson-yang-extensions { 
            prefix yexte; 
            revision-date "2018-02-19";
            }
            
}

In practical we have another use case : yang modeling file without specifying “@revision-date” as the file name, and the other module import with specifying the existed revision date, this case now is not supported by typefox.
Example:

Module  ericsson-yang-extensions {
Revision “2018-02-19” {
   description "second version.";
}
}

Module Ericsson-lm {
            …
            import ericsson-yang-extensions { 
            prefix yexte; 
            revision-date "2018-02-19";
            }
            
}

Can typefox be improved to support the second case ?

**Comment by JanKoehnlein** [comment]
I am a bit confused, as I think it is completely the other way around: We currently support linking against a revision statement, but not against the file name.

Anyway, I take it that you want both to be possible, so I will implement the 'revision by filename' case.

**Comment by JanKoehnlein** [comment]
Fixed

**Comment by sygsir** [comment]
Hi Jan,

Sorry for the late reply, now I come back to verify the use case with latest code. the problem still exists:

ERROR (org.eclipse.xtext.diagnostics.Diagnostic.Linking) 'Couldn't resolve reference to Revision '2016-09-27'.' on RevisionDate, offset 211, length 12

use case :

Module ericsson-yang-extensions {
      Revision “2018-02-19” {
                  description "second version.";
      }
}

Module Ericsson-lm {
     …
     import ericsson-yang-extensions {
                prefix yexte;
                revision-date "2018-02-19";
     }
}

**Comment by JanKoehnlein** [comment]
After adding prefix and namespace in both files, fixing the caps, and replacing the quotes around the revision date with regular ones it works like a charm here:

```
module ericsson-yang-extensions {
    prefix e;
    namespace "urn:e";
    revision "2018-02-19" {
        description "second version.";
    }
}
```
and 
```
module Ericsson-lm {
    prefix f;
    namespace "urn:e";
    import ericsson-yang-extensions {
    prefix yexte;
    revision-date "2018-02-19";
    }
}
```

**Comment by JanKoehnlein** [comment]
Aha, that's by design. For linking, we only consider the latest revision of a module. 
So `revision-date 2017-06-06` works as expected.

See our discussion on that on https://github.com/theia-ide/yang-lsp/issues/99
